# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"

target "seq.temp_caseinsensitive_rename" do
pod 'Wit', '~> 1.2.0'
end

target "seq.temp_caseinsensitive_renameTests" do

end

